---
version: '3'

services:
  kong:
    image: kong:1.0.3
    restart: always
    command: sh -c "kong migrations bootstrap && kong start --run-migrations"
    depends_on:
      - postgres
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_LOG_LEVEL=debug
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - kong
    healthcheck:
      test: "kong health"
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks:
      - kong
    healthcheck:
      test: "pg_isready -U kong && psql -d kong -U kong -c \"SELECT 1=1\""
      interval: 10s
      timeout: 5s
      retries: 5

  kong-dashboard:
    image: pgbi/kong-dashboard
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - kong
    networks:
      - kong
    command: start --kong-url http://kong:8001

networks:
  kong:
