---
version: '2.2'
services:
  kong:
    image: kong:0.14-centos
    depends_on:
      kong-migration:
        condition: service_healthy
    restart: always
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_LOG_LEVEL=debug
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      - backend
      - public
    healthcheck:
      test: "kong health"
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:0.14-centos
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
    networks:
      - backend
    command: sh -c "kong migrations up && touch migrations_run && sleep 30"
    healthcheck:
      test: "if [[ -f migrations_run ]] ; then exit 0; else exit 1; fi"
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks:
      - backend
    healthcheck:
      test: "pg_isready -U kong && psql -d kong -U kong -c \"SELECT 1=1\""
      interval: 10s
      timeout: 5s
      retries: 5

  kong-dashboard:
    image: pgbi/kong-dashboard
    ports:
      - 8080:8080
    depends_on:
      kong:
        condition: service_healthy
    networks:
      - backend
      - public
    command: start --kong-url http://kong:8001

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
        gateway: 172.16.239.1
